// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { LoanPoints } from "./LoanPoints";
import type { LoanRegions } from "./LoanRegions";
import type { MovePoints } from "./MovePoints";
import type { MoveRegions } from "./MoveRegions";
import type { PermissionsBoundary } from "./PermissionsBoundary";
import type { PermissionsLineDisplay } from "./PermissionsLineDisplay";

export interface AnalysisOutput { body_range: CharRange, boundaries: Array<PermissionsBoundary>, steps: Array<PermissionsLineDisplay>, loan_points: LoanPoints, loan_regions: LoanRegions, move_points: MovePoints, move_regions: MoveRegions, }