// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundariesAnnotations } from "./BoundariesAnnotations";
import type { InterpAnnotations } from "./InterpAnnotations";
import type { MdLinePos } from "./MdLinePos";
import type { StepperAnnotations } from "./StepperAnnotations";

export interface AquascopeAnnotations { hidden_lines: Array<MdLinePos>, interp: InterpAnnotations, stepper: StepperAnnotations, boundaries: BoundariesAnnotations, }