// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharPos } from "./CharPos";
import type { FilenameIndex } from "./FilenameIndex";

export interface CharRange { start: CharPos, end: CharPos, filename: FilenameIndex, }