// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { FlowEdgeKind } from "./FlowEdgeKind";

export interface FlowBoundary { is_violation: boolean, flow_context: CharRange, kind: FlowEdgeKind, }