// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MdCharPos } from "./MdCharPos";

export interface InterpAnnotations { state_locations: Array<MdCharPos>, }