// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MValue } from "./MValue";

export interface MHeap { locations: Array<MValue>, }