// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MPathSegment } from "./MPathSegment";
import type { MValue } from "./MValue";

export interface MLocal { name: string, value: MValue, moved_paths: Array<Array<MPathSegment>>, }