// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { MoveKey } from "./MoveKey";

export type MovePoints = Record<MoveKey, CharRange>;