// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MUndefinedBehavior } from "./MUndefinedBehavior";

export type MResult = { "type": "Success" } | { "type": "Error", "value": MUndefinedBehavior };