// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MResult } from "./MResult";
import type { MStep } from "./MStep";

export interface MTrace<L> { steps: Array<MStep<L>>, result: MResult, }