// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MUndefinedBehavior = { "type": "PointerUseAfterFree", "value": { alloc_id: number, } } | { "type": "Other", "value": string };