// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathMatcher = { type: "Literal", value: string } | { type: "Regex", value: string };