// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { PermissionsDataDiff } from "./PermissionsDataDiff";

export interface PermissionsStepTable { from: CharRange, to: CharRange, state: Array<[string, PermissionsDataDiff]>, }