// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharRange } from "./CharRange";
import type { Refiner } from "./Refiner";

export interface RefinementRegion { refiner_point: Refiner, refined_ranges: Array<CharRange>, }