// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MdLinePos } from "./MdLinePos";
import type { PathMatcher } from "./PathMatcher";

export interface StepperAnnotations { focused_lines: Array<MdLinePos>, focused_paths: Record<MdLinePos, Array<PathMatcher>>, }