// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeInfo } from "./TypeInfo";

export interface CallTypes { expected: TypeInfo, actual: TypeInfo, }