// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MValue } from "./MValue";

export interface MFrame<L> { name: string, location: L, locals: Array<[string, MValue]>, }