// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MHeapAllocKind = { type: "String", value: { len: bigint, } } | { type: "Vec", value: { len: bigint, } } | { type: "Box" };
