// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingPermReason } from "./MissingPermReason";

export interface MissingPermsInfo { read?: MissingPermReason, write?: MissingPermReason, drop?: MissingPermReason, }