// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MPathSegment = { type: "Field", value: number } | { type: "Index", value: number };