// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MHeap } from "./MHeap";
import type { MStack } from "./MStack";

export interface MStep<L> { stack: MStack<L>, heap: MHeap, }