// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";
import type { RefinementInfo } from "./RefinementInfo";

export interface PermissionsInfo { range: Range, read: boolean, write: boolean, drop: boolean, refined_by: RefinementInfo | null, }