// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueStep } from "./ValueStep";

export interface PermissionsDiff { read: ValueStep, write: ValueStep, drop: ValueStep, }