// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanKey } from "./LoanKey";
import type { PermissionsDiff } from "./PermissionsDiff";
import type { ValueStep } from "./ValueStep";

export interface PermissionsDataDiff { is_live: ValueStep<boolean>, type_droppable: ValueStep<boolean>, type_writeable: ValueStep<boolean>, path_moved: ValueStep<boolean>, loan_read_refined: ValueStep<LoanKey>, loan_write_refined: ValueStep<LoanKey>, loan_drop_refined: ValueStep<LoanKey>, permissions: PermissionsDiff, }