// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoolStep } from "./BoolStep";

export interface PermissionsDiff { read: BoolStep, write: BoolStep, drop: BoolStep, }