// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanKey } from "./LoanKey";
import type { PermissionsDiff } from "./PermissionsDiff";
import type { ValueStep } from "./ValueStep";

export interface PermissionsDataDiff { is_live: ValueStep, type_droppable: ValueStep, type_writeable: ValueStep, path_moved: ValueStep, loan_read_refined: ValueStep<LoanKey>, loan_write_refined: ValueStep<LoanKey>, loan_drop_refined: ValueStep<LoanKey>, permissions: PermissionsDiff, }