// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permissions } from "./Permissions";
import type { Range } from "./Range";
import type { RefinementInfo } from "./RefinementInfo";

export interface PermissionsBoundary { range: Range, expected: Permissions, actual: Permissions, was_copied: boolean, refined_by: RefinementInfo | null, }