// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

export interface RefinementRegion {
  loan_location: Range;
  start: Range;
  end: Range;
}
