// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";
import type { TypeState } from "./TypeState";

export interface TypeInfo {
  range: Range;
  of_type: TypeState;
}
