// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TypeState = { Owned: { mutably_bound: boolean, } } | { Ref: { is_mut: boolean, } };