// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ValueStep<A> = { type: "High" } | { type: "Low" } | { type: "None", value: A | null, };