name: run-on-remote
inputs:
  file:
    required: true
  credentials:
    required: true
  project-id:
    required: true
  ssh-key:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.credentials }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 412.0.0'
    - name: Copy to server
      run: gcloud compute scp ./${{ inputs.file }} gh-actions@aquascope:~/${{ inputs.file }} --zone us-central1-a --tunnel-through-iap
      shell: bash
    - name: Make executable
      uses: google-github-actions/ssh-compute@v0
      with:
        zone: 'us-central1-a'
        project_id: ${{ inputs.project-id }}
        ssh_private_key: ${{ inputs.ssh-key }}
        instance_name: aquascope
        user: gh-actions
        command: "chmod +x ~/${{ inputs.file }}"
    - name: Execute script
      uses: google-github-actions/ssh-compute@v0
      with:
        zone: 'us-central1-a'
        project_id: ${{ inputs.project-id }}
        ssh_private_key: ${{ inputs.ssh-key }}
        instance_name: aquascope
        user: gh-actions
        command: /home/gh-actions/${{ inputs.file }}
