[book]
authors = ["Will Crichton"]
language = "en"
src = "src"

[preprocessor.aquascope]
command = "cargo run --bin mdbook-aquascope"

[build]
extra-watch-dirs = ["../../../frontend/packages/aquascope-embed/dist"]
