// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Abbreviated<T> = { type: "All", value: Array<T> } | { type: "Only", value: [Array<T>, T] };