// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanPoints } from "./LoanPoints";
import type { LoanRegions } from "./LoanRegions";

export interface AnalysisOutput<O> { values: Array<O>, loan_points: LoanPoints, loan_regions: LoanRegions, }
