// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MValue } from "./MValue";
import type { Range } from "./Range";

export interface MFrame<L> { name: string, body_span: Range, location: L, locals: Array<[string, MValue]>, }