// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanKey } from "./LoanKey";
import type { Range } from "./Range";

export type MovePoints = Record<LoanKey, Range>;
