// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MMemorySegment } from "./MMemorySegment";
import type { MPathSegment } from "./MPathSegment";

export interface MPath { segment: MMemorySegment, parts: Array<MPathSegment>, }