// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MFrame } from "./MFrame";

export interface MStack<L> { frames: Array<MFrame<L>>, }
