// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoolStep } from "./BoolStep";

export interface PermissionsDataDiff { is_live: BoolStep, type_droppable: BoolStep, type_writeable: BoolStep, loan_read_refined: BoolStep, loan_write_refined: BoolStep, loan_drop_refined: BoolStep, path_moved: BoolStep, }