// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermDiff } from "./PermDiff";

export interface PermsDiff {
  read: PermDiff;
  write: PermDiff;
  drop: PermDiff;
}
