// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanKey } from "./LoanKey";
import type { Permissions } from "./Permissions";

export interface PermissionsData { type_droppable: boolean, type_writeable: boolean, type_copyable: boolean, is_live: boolean, path_moved: boolean, loan_read_refined?: LoanKey, loan_write_refined?: LoanKey, loan_drop_refined?: LoanKey, permissions: Permissions, }