// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingPermsInfo } from "./MissingPermsInfo";
import type { Permissions } from "./Permissions";

export interface PermissionsBoundary {
  location: number;
  expected: Permissions;
  actual: Permissions;
  was_copied: boolean;
  explanations: MissingPermsInfo;
}
