// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Range { char_start: number, char_end: number, byte_start: number, byte_end: number, filename: string, }
