// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefinementRegion } from "./RefinementRegion";

export interface RefinementInfo {
  read: RefinementRegion | null;
  write: RefinementRegion | null;
  drop: RefinementRegion | null;
}
