// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";

export type Refiner = ({ type: "Loan" } & Range) | ({ type: "Move" } & Range);
