// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";
import type { Refiner } from "./Refiner";

export interface RefinementRegion {
  refiner_point: Refiner;
  refined_ranges: Array<Range>;
  start: Range;
  end: Range;
}
